version: 0.2

env:
    variables:
        QUEUE_NAME: "errbot-facultybot.fifo"
        IRC_CHANNEL: "#seantest"

phases:
  install:
    commands:
      - system/build/install_base
      - system/build/conditional_phase install
  pre_build:
    commands:
      - system/build/conditional_phase pre_build
  build:
    commands:
      - system/build/conditional_phase build
  post_build:
    commands:
      - system/build/conditional_phase post_build
      - system/build/conditional_phase finalizing
