version: 0.2

env:
    variables:
        QUEUE_NAME: "errbot-facultybot.fifo"
        IRC_CHANNEL: "#seantest"

phases:
  install:
    commands:
      - pip install https://s3.amazonaws.com/faculty-captured/faci-1.1.0.tar.gz
      - faci notify
      - faci phase install
  pre_build:
    commands:
      - faci phase pre_build
  build:
    commands:
      - faci phase build
  post_build:
    commands:
      - faci phase post_build
      - faci finalize
