# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      BOT_IRC_CHANNEL: ops
      BOT_CLIENT_SECRET: ${{ secrets.BOT_CLIENT_SECRET }}

    steps:
      - name: setup
        run: |
          wget --quiet https://custom-packages.faculty.net/botsay-0.1.0
          chmod +x botsay-0.1.0
          sudo mv botsay-0.1.0 /bin/botsay

      - name: tell IRC
        run: 'botsay "Build starting: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'



  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: lambci/lambda:build-python3.8
    env:
      IRC_CHANNEL: seantest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup
        run: |
          pip install aws-sam-cli awscli boto3 botocore --force-reinstall --upgrade

#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
